
spring:
#  rsocket:
#    server:
#      port: 6565
  application:
    name: rsocket-server-app

eureka:
#  instance:
#    hostname: ${spring.application.name}:${random.value}
#    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
